---
version: "3.1"

services:
  jenkins:
    build:
      context: jenkins/
      args:
        VERSION: 2.492.1-lts-alpine
    ports:
      - "4040:4040"
    depends_on:
      - keycloak
    environment:
      GITEA_PASSWORD: "${USER_PASSWORD}"
      KEYCLOAK_JENKINS_SECRET: "${JENKINS_CLIENT_SECRET}"
    security_opt:
      - label=disable
    volumes:
      - "./worker/ssh/test-key:/run/secrets/ssh_private_key:ro"

  worker:
    build:
      context: worker/
      args:
        FEDORA_VERSION: 41
    cap_add:
      - SYS_CHROOT

  gitea:
    build:
      context: gitea/
      args:
        VERSION: 1.23.3
    cap_add:
      - SYS_CHROOT
    environment:
      DB_TYPE: postgres
      DB_HOST: db:5432
      DB_NAME: gitea
      DB_USER: gitea
      SSH_PORT: 2222
      ROOT_URL: http://localhost:3000
      GITEA__webhook__ALLOWED_HOST_LIST: private
      GITEA_PASSWORD: "${GITEA_ADMIN_PASSWORD}"
      LDAP_BIND_CREDENTIAL: "${LDAP_ADMIN_PASSWORD}"
      USER_PASSWORD: "${USER_PASSWORD}"
      DB_PASSWD: "${GITEA_DB_PASSWORD}"
      RUN_MODE: "prod"
      DISABLE_REGISTRATION: "true"
      INSTALL_LOCK: "true"
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_GITEA_SECRET: "${GITEA_CLIENT_SECRET}"
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db
      - keycloak
      - ldap

  db:
    image: postgres:14.15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      GITEA_DB_PASSWORD: "${GITEA_DB_PASSWORD}"
      KEYCLOAK_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: >
        --auth-host=scram-sha-256 --auth-local=scram-sha-256
    security_opt:
      - label=disable
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  ldap:
    build:
      context: ldap/
    environment:
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
      USER_PASSWORD: "${USER_PASSWORD}"
      LDAP_SEED_INTERNAL_LDIF_PATH: /tmp/ldifs

  keycloak:
    build:
      context: keycloak/
      args:
        VERSION: 26.1.2
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      KEYCLOAK_IMPORT: /tmp/ci-realm.json
      KEYCLOAK_JENKINS_SECRET: "${JENKINS_CLIENT_SECRET}"
      KEYCLOAK_GITEA_SECRET: "${GITEA_CLIENT_SECRET}"
      LDAP_BIND_CREDENTIAL: "${LDAP_ADMIN_PASSWORD}"
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      - db
