FROM jenkins/jenkins:lts-alpine

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY plugins/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt 

COPY jcasc/ /var/jenkins_home/casc_configs
COPY project/ /tmp/localrepo
USER root
RUN chown jenkins:jenkins /tmp/localrepo
USER jenkins

RUN cd /tmp/localrepo && \
	git init && \
	git config --global user.name "prename surname" && \
	git config --global user.email "me@localhost" && \
	git add * && \
	git commit -m "initial commit"

ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc_configs
