FROM fedora:latest

RUN dnf install -y openssh-server && \
    ssh-keygen -A
RUN useradd jenkins
COPY ssh/test-key.pub /home/jenkins/.ssh/authorized_keys
RUN chown jenkins:jenkins /home/jenkins/.ssh/authorized_keys

EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
