#!/bin/bash
set -e
mkdir ssh/
ssh-keygen -t rsa -m PEM -f ssh/test-key -N ""

USER_PASSWORD="$(openssl rand -hex 16)"
MYSQL_ADMIN_PASSWORD="$(openssl rand -hex 16)"
MYSQL_USER_PASSWORD="$(openssl rand -hex 16)"
GITEA_USER_PASSWORD="$(openssl rand -hex 16)"
KEYCLOAK_PASSWORD="$(openssl rand -hex 16)"
KEYCLOAK_CLIENT_SECRET="$(uuidgen)"

echo
echo "+----------+-------+----------------------------------+"
echo "| Service  | User  | Generated password               |"
echo "+----------+-------+----------------------------------+"
echo "| Jenkins  | demo  | $USER_PASSWORD |"
echo "| Keycloak | admin | $KEYCLOAK_PASSWORD |"
echo "| Mysql    | root  | $MYSQL_ADMIN_PASSWORD |"
echo "| Mysql    | gitea | $MYSQL_USER_PASSWORD |"
echo "| Gitea    | gitea | $GITEA_USER_PASSWORD |"
echo "+----------+-------+----------------------------------+"
echo

cat >docker-compose.yml <<EOF
version: "3.1"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    environment:
      GITEA_PASSWORD: "$GITEA_USER_PASSWORD"
      REAL_KEYCLOAK_URL_PREFIX: "http://keycloak:8080/auth/realms/ci/protocol/openid-connect"
      USER_KEYCLOAK_URL_PREFIX: "http://localhost:10000/auth/realms/ci/protocol/openid-connect"
      KEYCLOAK_CLIENT_SECRET: "$KEYCLOAK_CLIENT_SECRET"
      SSH_PRIVATE_KEY: |-
$(sed "s/^/        /" ssh/test-key)

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker

  gitea:
    build:
      context: .
      dockerfile: Dockerfile-gitea
    environment:
      DB_TYPE: mysql
      DB_HOST: db:3306
      DB_NAME: gitea
      DB_USER: gitea
      SSH_PORT: 2222
      ROOT_URL: http://gitea:3000
      GITEA_USER: gitea
      GITEA_PASSWORD: "$GITEA_USER_PASSWORD"
      DB_PASSWD: "$MYSQL_USER_PASSWORD"
      RUN_MODE: "prod"
      DISABLE_REGISTRATION: "true"
      INSTALL_LOCK: "true"
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db
      - keycloak

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ADMIN_PASSWORD"
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: "$MYSQL_USER_PASSWORD"

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    environment:
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_HTTP_PORT: 10000
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: "$KEYCLOAK_PASSWORD"
      KEYCLOAK_IMPORT: /tmp/ci-realm.json
      KEYCLOAK_CLIENT_SECRET: "$KEYCLOAK_CLIENT_SECRET"
      USER_PASSWORD: "$USER_PASSWORD"
    ports:
      - "10000:8080"
EOF
