jenkins:
  crumbIssuer: standard
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${ADMIN_PASSWORD}
  authorizationStrategy: loggedInUsersCanDoAnything

credentials:
  system:
    domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            scope: GLOBAL
            id: test-key
            username: jenkins
            description: "Test SSH credentials"
            privateKeySource:
              directEntry:
                privateKey: ${SSH_PRIVATE_KEY}

security:
  remotingCLI:
    enabled: false

unclassified:
  location:
    url: http://localhost:8080
