jenkins:
  crumbIssuer: standard
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: admin
        password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admingroup"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "everybody"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Build"
            assignments:
              - "anonymous"

  nodes:
    - permanent:
        name: "worker-1"
        remoteFS: "/home/jenkins"
        labelString: "fedora"
        launcher:
          SSHLauncher:
            host: "worker"
            credentialsId: "agent-ssh-key"
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          scope: SYSTEM
          id: agent-ssh-key
          username: jenkins
          description: "Test SSH credentials"
          privateKeySource:
            directEntry:
              privateKey: ${SSH_PRIVATE_KEY}
      - usernamePassword:
          id: "gitea-login"
          password: ${GITEA_PASSWORD}
          scope: GLOBAL
          username: "gitea"

security:
  remotingCLI:
    enabled: false

unclassified:
  location:
    url: http://localhost:8080
  giteaServers:
    servers:
      - credentialsId: "gitea-login"
        displayName: "mygitea"
        manageHooks: true
        serverUrl: "http://gitea:3000"
