jenkins:
  crumbIssuer: standard
  remotingSecurity:
    enabled: true
  securityRealm:
    oic:
      clientId: jenkins
      clientSecret: ${KEYCLOAK_JENKINS_SECRET}
      automanualconfigure: manual
      tokenServerUrl: ${REAL_KEYCLOAK_URL_PREFIX}/token
      userInfoServerUrl: ${REAL_KEYCLOAK_URL_PREFIX}/userinfo
      authorizationServerUrl: ${USER_KEYCLOAK_URL_PREFIX}/auth
      endSessionEndpoint: ${USER_KEYCLOAK_URL_PREFIX}/logout
      postLogoutRedirectUrl: http://localhost:4040
      logoutFromOpenidProvider: true
      userNameField: preferred_username
      fullNameFieldName: fullName
      emailFieldName: email
      scopes: openid email
  authorizationStrategy: loggedInUsersCanDoAnything

  nodes:
    - permanent:
        name: "worker-1"
        remoteFS: "/home/jenkins"
        labelString: "fedora"
        launcher:
          SSHLauncher:
            host: "worker"
            credentialsId: "agent-ssh-key"
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false

credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          scope: SYSTEM
          id: agent-ssh-key
          username: jenkins
          description: "Test SSH credentials"
          privateKeySource:
            directEntry:
              privateKey: ${SSH_PRIVATE_KEY}
      - usernamePassword:
          id: "gitea-login"
          password: ${GITEA_PASSWORD}
          scope: GLOBAL
          username: "gitea"

unclassified:
  location:
    url: http://localhost:4040
  giteaServers:
    servers:
      - credentialsId: "gitea-login"
        displayName: "mygitea"
        manageHooks: true
        serverUrl: "http://localhost:3000"
