jenkins:
  crumbIssuer: standard
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: admin
        password: ${ADMIN_PASSWORD}
  authorizationStrategy: loggedInUsersCanDoAnything

credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          scope: GLOBAL
          id: test-key
          username: jenkins
          description: "Test SSH credentials"
          privateKeySource:
            directEntry:
              privateKey: ${SSH_PRIVATE_KEY}
      - usernamePassword:
          id: "gitea-login"
          password: ${GITEA_PASSWORD}
          scope: GLOBAL
          username: "gitea"

security:
  remotingCLI:
    enabled: false

unclassified:
  location:
    url: http://localhost:8080
  giteaServers:
    servers:
      - credentialsId: "gitea-login"
        displayName: "mygitea"
        manageHooks: true
        serverUrl: "http://gitea:3000"
