---
jobs:
  - script: >
      organizationFolder("Gitea Test") {
        description("Organization Folder")
        configure {
          it / navigators / "org.jenkinsci.plugin.gitea.GiteaSCMNavigator" << {
            repoOwner("home")
            serverUrl("http://localhost:3000")
            credentialsId("gitea-login")
          }

          it / navigators / "org.jenkinsci.plugin.gitea.GiteaSCMNavigator" /
              traits  << "org.jenkinsci.plugin.gitea.BranchDiscoveryTrait" {
            strategyId('3')
          }
        }
      }
