#!/bin/sh
sed "s/\$USER_PASSWORD/$USER_PASSWORD/;s/\$KEYCLOAK_JENKINS_SECRET/$KEYCLOAK_JENKINS_SECRET/;s/\$KEYCLOAK_GITEA_SECRET/$KEYCLOAK_GITEA_SECRET/" /opt/ci/ci-realm.json >/tmp/ci-realm.json
exec /opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0
#-Djboss.socket.binding.port-offset=10
