def remote = [:] 
remote.host = "worker"
remote.name = "worker"
remote.allowAnyHosts = true

node {
    dir('sub') {
        // Workaround to find files of own repository under sub/
        checkout scm
    }

    withCredentials([sshUserPrivateKey(credentialsId: 'test-key', keyFileVariable: 'identity', passphraseVariable: '', usernameVariable: 'jenkins')]) {
        remote.user = jenkins
        remote.identityFile = identity
        stage("execute script on remote host") {
            sshScript remote: remote, script: 'sub/script.sh'
        }

        stage("execute some more commands on a worker") {
            sshCommand remote: remote, command: 'cat /etc/hostname'
            sshCommand remote: remote, command: 'sleep 3'
        }
    }   
}
