#!/bin/bash
if [[ "$GITEA_USER" && "$GITEA_PASSWORD" ]]; then
    while true; do
        nc localhost 3000 </dev/null && break
        sleep 1
    done

    if gitea admin create-user --name "$GITEA_USER" --password "$GITEA_PASSWORD" --email me@localhost >/tmp/init.log
    then
        GITEA_URL="http://localhost:3000"
        AUTHORIZATION="$(echo -n "$GITEA_USER:$GITEA_PASSWORD" | base64)"

        DEFAULT_CURL_PARAMETERS=(-H Content-Type:application/json -H accept:application/json)
        TOKEN="$(curl -sf -X POST --url $GITEA_URL/api/v1/users/gitea/tokens -H "Authorization: Basic $AUTHORIZATION" \
            "${DEFAULT_CURL_PARAMETERS[@]}" --data '{"name":"test"}' | sed "s/}//g;s/\"//g" | awk -F: '{ print $NF }')"
        [ -z "$TOKEN" ] && echo "Could not create token"

        curl -f -X POST "$GITEA_URL/api/v1/orgs" -H "Authorization: token $TOKEN" "${DEFAULT_CURL_PARAMETERS[@]}" \
            --data '{"name": "org", "username": "home"}'
        curl -f -X POST "$GITEA_URL/api/v1/org/home/repos?token=$TOKEN" "${DEFAULT_CURL_PARAMETERS[@]}" \
            -d '{"name":"test", "description": "Test repository"}'
        curl -f -X POST "$GITEA_URL/api/v1/org/home/repos?token=$TOKEN" "${DEFAULT_CURL_PARAMETERS[@]}" \
            -d '{"name":"test2", "description": "Second test repository"}'

        git config --global user.email "me@localhost"
        git config --global user.name "Prename Surname"

        ssh-keygen -f "$HOME/.ssh/id_rsa" -N ''
        PUBLIC_SSH_KEY="$(cat "$HOME/.ssh/id_rsa.pub")"

        curl -f -X POST  "$GITEA_URL/api/v1/user/keys?token=$TOKEN" "${DEFAULT_CURL_PARAMETERS[@]}" \
            -d "{\"Title\": \"test-key\", \"Key\": \"$PUBLIC_SSH_KEY\"}"

        cat > "$HOME/.ssh/config" <<EOF
Host localhost
  StrictHostKeyChecking=no
EOF

        for repo in test test2; do
            git clone ssh://git@localhost/home/$repo /tmp/$repo
            pushd "$PWD" || exit
            cd "/tmp/$repo" || exit
            cat >Jenkinsfile <<EOF
pipeline {
    agent { label "fedora" }

    stages {
        stage("Build") {
            steps {
                sh "echo Hello World! This is repo $repo"
            }
        }
    }
}
EOF
            git add Jenkinsfile
            git commit -m "initial commit"
            git push
            popd || exit
        done

        curl -f -X POST "$GITEA_URL/api/v1/orgs/home/hooks?token=$TOKEN" "${DEFAULT_CURL_PARAMETERS[@]}" \
            -d "{\"active\": true, \"type\": \"gitea\", \"config\": \
                { \"url\": \"http://jenkins:8080/gitea-webhook/post\", \"content_type\": \"json\" } }"
    fi
fi

while true; do
    sleep 3600
done
